tools:
  golint:
    enabled: true
    parameters: './...'
  staticcheck:
    enabled: true
    parameters: './...'
  go vet:
    enabled: true
    parameters: './...'
  unused:
    enabled: true
    parameters: './...'
  unparam:
    enabled: true
    parameters: './...'
  errcheck:
    enabled: true
    parameters: './...'
