tools:
  golint:
    enabled: true
    parameters: './...'
  staticcheck:
    enabled: true
    parameters: './...'
  go vet:
    enabled: true
    parameters: './...'
  errcheck:
    enabled: true
    parameters: './...'
